//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lottery1
    {
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public int LotteryGiftID { get; set; }
        public System.DateTime LotteryDate { get; set; }
        public bool Share { get; set; }
        public bool Receive { get; set; }
        public Nullable<int> UberID { get; set; }
    }
}
